services:
  backend:
    build:
      context: ./backend

    container_name: issue-tracker-backend

    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend

    container_name: issue-tracker-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"